Malkith99/Job-Portal-System-FRONTEND

- package-lock.json
- src/components/footer/footer.css
- src/components/pages/student/home/StudentHome.js
- src/components/pages/student/home/studentHome/feed2.js
- src/components/pages/student/home/studentHome/feeds.css
- src/components/pages/student/home/studentHome/feeds.js
- src/components/pages/student/home/studentHome/feeds2.css
- src/components/pages/student/profile/studentProfile.js
- src/components/pages/student/profileImage/profileImage.js
- src/components/pages/student/profileImage/profileImageMain.js
add some pages of student side. have to check if there any difference
> 002 asanka

- src/components/pages/student/profile/Person_popup.js
- src/components/pages/student/profile/studentProfile.js
get data of DOB ad index prom popup and then update with back
> Student Profile update

- src/components/Home/home.css
- src/components/SignUpSignIn/SignInSignUp.css
- src/components/mainHeader/title/title.css
making rersponsive only text of the title in the header and the text in home page buttons
> make responsive to the titile and button

- src/components/pages/company/companyLogin/companyLogin.js
> Company_login_page

- src/components/pages/student/StudentSignIn/StudentSignIn.js
> Student_Login_page

- src/components/pages/student/StudentSignIn/StudentSignIn.js
Student login page text fields changed
> Student login page text fields changed

- src/components/Home/Home.js
- src/components/Home/home.css
- src/components/carousel/carousel.js
removed moving text from the header bottom and make carousel responsive
> removing moving text,make carousel responsive

- src/components/availableCompanies/availabaleCompanies.css
- src/components/availableCompanies/availableCompanies.js
change the style of box of available companies
> change the style of box of available companies

- src/components/availableCompanies/availabaleCompanies.css
- src/components/availableCompanies/availableCompanies.js
- src/components/mainHeader/title/title.css
- src/components/mainHeader/title/title.js
> removed underline in title

- src/components/availableCompanies/availabaleCompanies.css
- src/components/availableCompanies/availableCompanies.js
- src/components/footer/footer.css
- src/components/footer/footer.js
- src/components/mainHeader/title/title.css
- src/components/mainHeader/title/title.js
change the styles in the footer
> change the styles in the footer

- src/components/pages/student/home/studentHome/Feed.css
- src/components/pages/student/home/studentHome/Feed.js
company vacancy card in student home pge
> company vacancy card in student home pge

- src/components/pages/student/home/StudentHome.css
- src/components/pages/student/home/StudentHome.js
- src/components/pages/student/home/studentHome/Feed.css
- src/components/pages/student/home/studentHome/Feed.js
Adjusted the search bar and image
> Adjusted the search bar and image

- src/App.js
- src/components/pages/company/companyLogin/companyLogin.js
- src/components/pages/company/companySignup/companySignup.js
- src/components/pages/company/home/CompanyMainHome.js
routing path of Company home  changed to new company home page
> fixong company side(routing)

- src/App.js
- src/components/mainHeader/title/title.css
- src/components/pages/lecturer/lectureDetails/LecturerProfile.js
- src/components/pages/lecturer/lecturerSignup/lecturerSignup.js
- src/components/pages/student/StudentSignIn/StudentSignIn.js
- src/components/pages/student/StudentSignUp/SignUp/StudentSignUp.js
there were unwanted link in signup pages.it removed and make route correctly
> 004 asanka

- package-lock.json
- package.json
- src/components/pages/lecturer/home/lecturerHome/LecturerHome.js
- src/components/pages/studentApplication/StudentApplicationLecturer.js
> added popup message when lecturer approved someone

- src/components/mainHeader/title/title.css
- src/components/pages/company/companyLogin/companyLogin.js
- src/components/pages/company/home/companyHome/CompanyHomePage.js
- src/components/pages/company/home/companyHome/ResponsesVac.css
- src/components/pages/lecturer/lecturerLogin/lecturerLogin.js
- src/components/pages/student/StudentSignIn/StudentSignIn.js
make response in lecturer login and there some errors in title when decreasing the size of the page,
it was fixed
> make response in lecturer login

- src/components/pages/student/profile/StudentProfile.css
- src/components/pages/student/profile/studentProfile.js
> Student_Profile_css added

- src/components/pages/company/home/companyHome/CompanyHomePage.css
- src/components/pages/lecturer/home/lecturerHome/LecturerHome.js
- src/components/pages/studentApplication/StudentApplicationLecturer.js
adjust some mistakes in company home.
> 010 asanka

- src/components/SignUpSignIn/AllSignIn.jsx
- src/components/pages/student/StudentSignIn/StudentSignIn.js
- src/components/pages/student/home/studentHome/Feed.css
- src/components/pages/student/home/studentHome/Feed.js
- src/components/pages/student/profile/studentProfile.js
Reverts Malkith99/Job-Portal-System-FRONTEND#156
> Revert "Aug15th"

- src/components/pages/Admin/AdminHome/adminHome.css
- src/components/pages/Admin/AdminHome/adminHome.js
> create admin page using new css

- src/components/pages/student/home/studentHome/Feed.css
- src/components/pages/student/home/studentHome/Feed.js
detete duplicate cards and adjust the card
> fixed companies cards for student page

- src/components/SignUpSignIn/AllSignIn.jsx
- src/components/SignUpSignIn/AllSignin.css
- src/components/availableCompanies/availabaleCompanies.css
- src/components/mainHeader/title/title.css
no any deletion in signin page.just change css files.
> make all signin page better and titile responsively

- src/components/pages/company/companyProfile/companyProfile/CompanyProfile.js
- src/components/pages/company/home/companyHome/VavancySection/VacancySection.js
- src/components/pages/student/home/studentHome/VavancySection/VacancySection.js
three pages were fixed.
company profile
vacancy page for student
vacancy page for company
> make company profile and vacany pages neetly
